Breaking up teams step
JupiterOne/graph-github pull request #107
Opened 2021-11-15 23:15 UTC by kevincasey1222

Separating the fetch-teams step into 3 steps : fetch-teams, fetch-team-members, and fetch-team-repos

This will help isolate errors, because fetch-teams for just the entities is actually pretty quick compared to the other two.

2021-11-16 15:30 UTC, aiwilliams submitted a review, later dismissed
A couple of questions but LGTM. May be good to get a review from @mknoedel , whom I've requested it from.

2021-11-16 15:31 UTC, aiwilliams commented
Just learned that @austinkelleher has been helping on this integration, so requested review from him.

2021-11-16 16:56 UTC, kevincasey1222 commented on src/steps/teams.ts
> -      }
Yep

2021-11-17 18:26 UTC, austinkelleher requested changes
Thanks for improving this!

2021-11-17 18:26 UTC, austinkelleher commented on src/client/OrganizationAccountClient.ts
> +          `Repo ${repoName} returned a 403 unauthorized when environmental secrets requested.`,
Can we change this to have `repoName` as an object property in the first arg? We should avoid string interpolation/concatenation of log messages when possible. Static log messages are easier and faster to search for. 

Searching for an exact match of `"Repo returned a 403 unauthorized when environmental secrets requested."` is faster than leveraging the "contains partial" operator and searching for something like `"returned a 403 unauthorized when environmental secrets requested."`

```suggestion
          { repoName },
          'Repo returned a 403 unauthorized when environmental secrets requested.',
```

2021-11-17 18:26 UTC, austinkelleher commented on src/client/OrganizationAccountClient.ts
> +      const repoEnvSecrets = await this.v3.paginate(
Nice variable rename

2021-11-17 18:26 UTC, austinkelleher commented on src/steps/teamMembers.ts
> +      await jobState.addEntity(toOrganizationMemberEntityFromTeamMember(user));
I think the main implication is around partial datasets. If this step fails, the `github_user` `_type` will be marked as partial and the persister will not process deletes of `github_user`.

2021-11-17 18:26 UTC, austinkelleher commented on src/steps/teamRepos.ts
> +        `Expected repo (CodeRepo) with id to exist (key=${teamRepo.id})`,
I realize this is old code, but now that I'm reviewing it...

I think that it's possible that a new repo between between the time that the repo step finished, and this step starts. The timing of that would cause this entire step to fail. I think we should just `warn` here. If it happens a lot, then it may be an indication that we have a wider issue, but I don't think we should fail the entire step in this case.

2021-11-17 18:26 UTC, austinkelleher commented on src/steps/teamRepos.ts
> +    if (!jobState.hasKey(teamRepo.id)) {
`hasKey` is `async`. Can we please `await` this?

2021-11-17 18:26 UTC, austinkelleher commented on src/steps/teamRepos.ts
> +    if (!jobState.hasKey(teamRepo.teams)) {
`hasKey` is `async`. Can we please `await` this?

2021-11-17 18:26 UTC, austinkelleher commented on src/steps/teamRepos.ts
> +        `Expected team (UserGroup) with id to exist (key=${teamRepo.teams})`,
Same comment as above about not failing the entire step if we are missing the key.

2021-11-17 20:21 UTC, kevincasey1222 commented on src/steps/teamMembers.ts
> +      await jobState.addEntity(toOrganizationMemberEntityFromTeamMember(user));
Good point. Thanks.

2021-11-17 20:24 UTC, kevincasey1222 commented on src/client/OrganizationAccountClient.ts
> +          `Repo ${repoName} returned a 403 unauthorized when environmental secrets requested.`,
Great point - since I'm not directly using Cloudwatch, I didn't think of that.

2021-11-17 20:33 UTC, kevincasey1222 commented on src/steps/teamRepos.ts
> +        `Expected repo (CodeRepo) with id to exist (key=${teamRepo.id})`,
Agree.

2021-11-17 20:33 UTC, kevincasey1222 commented on src/steps/teamRepos.ts
> +    if (!jobState.hasKey(teamRepo.teams)) {
Yes! Thanks for catching that

2021-11-17 20:37 UTC, kevincasey1222 commented on src/steps/teamRepos.ts
> +    if (!jobState.hasKey(teamRepo.id)) {
Yes! Turns out, that mistake was in a few steps, including collaborators, which has been slow lately... hmmm... fixed everywhere.

2021-11-17 20:38 UTC, kevincasey1222 commented on src/steps/teamRepos.ts
> +        `Expected team (UserGroup) with id to exist (key=${teamRepo.teams})`,
Done.

2021-11-17 20:52 UTC, kevincasey1222 commented
Updated those `await jobstate.hasKey` calls, improved logs, and made improvements per your comments above.

2021-11-18 18:59 UTC, austinkelleher approved these changes

2021-11-18 18:59 UTC, austinkelleher commented on src/util/sleepIfApproachingRateLimit.ts
> +        await sleep(msUntilRateLimitReset);
Thank you!

2021-11-18 19:00 UTC, merged

2021-11-18 20:29 UTC, aiwilliams commented on src/steps/teamMembers.ts
> +      await jobState.addEntity(toOrganizationMemberEntityFromTeamMember(user));
Thanks, updated the development guide outline.