INT-1677 - Pull Request step step is too slow
JupiterOne/graph-github pull request #40
Opened 2021-08-30 19:51 UTC by mknoedel

Added rolling ingestion to the  pull request step.

Also rewrote the `organizationClient` to take the whole integrationContext instead of the logger, jobState, config and execution history as it was starting to get hard to follow.

2021-08-30 19:52 UTC, mknoedel commented on docs/jupiterone.md
> +https://github.com/JupiterOne/sdk/blob/master/docs/integrations/development.md
Why did this go to master? Do I need to update the sdk package?

- [ ] switch this back to main

2021-08-30 19:54 UTC, mknoedel commented on src/client.ts
> +        if (pr) {
PRs can now be undefined if they're created date is before the last successful execution date.

2021-08-30 19:54 UTC, mknoedel commented on src/client.ts
> -}
Removed this method as it doesn't do anything

2021-08-30 19:55 UTC, mknoedel commented on src/client/OrganizationAccountClient.test.ts
> +    expect(((client as any).teams = teamsResponse));
Needed to check that `client.teams` wasn't undefined as it would throw an error under some circumstances.

2021-08-30 20:16 UTC, ndowmon commented on docs/jupiterone.md
> +https://github.com/JupiterOne/sdk/blob/master/docs/integrations/development.md
Yep. The dependencies were recently updated. You probably just need to install the present dependencies.

2021-08-30 20:18 UTC, mknoedel commented on src/client/OrganizationAccountClient.ts
> +          direction: 'desc', // newest to oldest
These are the defaults but it seemed like it would be better to be explicit here.

2021-08-30 20:19 UTC, mknoedel commented on src/client/OrganizationAccountClient.ts
> +          }
There isn't a way to only query for PRs up to a specific day so it made sense to just always pull 100 and then check the `created_at` value, as it doesn't affect the rate limiting at all.

2021-08-30 20:21 UTC, mknoedel commented on docs/jupiterone.md
> +https://github.com/JupiterOne/sdk/blob/master/docs/integrations/development.md
Turns out you do just need to upgrade the sdk packages.

2021-08-30 20:30 UTC, ndowmon commented
> **mknoedel** 7 minutes ago Author Member
Turns out you do just need to upgrade the sdk packages.

@mknoedel FWIW You didn't need to bump the packages, just run 
```
rm -rf node_modules
yarn install --force
```

Since I think you just hadn't installed packages since they were bumped to `6.16.1`. Bumping to `6.18.0` is fine though

2021-08-30 21:03 UTC, ndowmon requested changes

2021-08-30 21:03 UTC, ndowmon commented on src/client/OrganizationAccountClient.ts
>            per_page: prCount,
It's a shame that this v3 API does not allow us to filter on `created` or `updated` properties, since the UI does allow us to filter like `updated:>=2013-02-01`. Maybe this will be available in the future.

2021-08-30 22:04 UTC, mknoedel commented on src/client/OrganizationAccountClient.test.ts
> +    expect(((client as any).teams = teamsResponse));
I think storing these entities in the client is an artifact from moving from sdk v1 to sdk v2. There doesn't seem to be any real value in doing this as far as I can tell, especially because we now have the job state. 

I'll take a look into how difficult it will be to removing `teams` an the other entity related properties from `OrganizationAccountClient`

2021-08-30 22:35 UTC, mknoedel commented on src/client/OrganizationAccountClient.test.ts
> +    expect(((client as any).teams = teamsResponse));
Yeah, that is not an ideal pattern. Looking into why it was likely done this way, It looks like these entity storage properties like `teams` and `repositories` were put into the client because we attempt to get all (except for Pull Request) Github data in a single graphQL call `getAccount`, which retrieves
```
        this.members = members;
        this.teams = teams;
        this.teamMembers = teamMembers;
        this.repositories = repositories;
        this.account = organization![0];
```

Each individual step will then either just iterate what was already fetched from the `fetch-account` step, or, if it doesn't see any stored values, it will attempt to fetch those values again using graphQL. I think this may have been ported over incorrectly, so we might be double-fetching data right now. This should get fixed

- [ ] Make sure we are not double pulling data.

As for if it is important at all to pull a ton of data in a single API call in the `getAccount` step, we do need to be hyper cognizant of how many api calls we are making to Github as they have very aggressive rate limiting, so grabbing as much data as possible in a single API call is definitely a good thing. The entities that are being stored are fairly small in number so it will be unlikely that we will run into any memory concerns by storing these values (plus we have had it out in production storing these values and we haven't run into any memory issues yet).

![image](https://user-images.githubusercontent.com/25489482/131413804-7b16192e-8618-4dbd-8046-17874c90abc5.png)

I think the solution to this is two-fold:
1. Shove these previously client-stored values into the jobState.
2. Do not attempt to re-pull for data that was already fetched in `getAccount`
2.5. Name `getAccount` something more description of what it is actually doing.

2021-08-30 22:36 UTC, mknoedel commented on src/client/OrganizationAccountClient.ts
> +          direction: 'desc', // newest to oldest
Updated makes way more sense, I'll update that.

2021-08-31 14:18 UTC, ndowmon commented on src/client/OrganizationAccountClient.test.ts
> +    expect(((client as any).teams = teamsResponse));
>Shove these previously client-stored values into the jobState.

Are you suggesting adding this raw array of `teams` to the job state, or adding the `github_team` entities, and referencing them in downstream steps as `await jobState.iterateEntities({ _type: 'github_team' }, async () => { ... })`?

2021-09-15 19:17 UTC, mknoedel commented
No longer needed

2021-09-15 19:17 UTC, closed without merging